/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtistSlugRouteImport } from './routes/artist.$slug'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedFavouritesRouteImport } from './routes/_authenticated/favourites'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth.me'
import { Route as AuthenticatedBookingArtistIdRouteImport } from './routes/_authenticated/booking.$artistId'
import { Route as AuthenticatedBookingIdConfirmRouteImport } from './routes/_authenticated/booking.$id.confirm'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistSlugRoute = ArtistSlugRouteImport.update({
  id: '/artist/$slug',
  path: '/artist/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFavouritesRoute = AuthenticatedFavouritesRouteImport.update({
  id: '/favourites',
  path: '/favourites',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBookingArtistIdRoute =
  AuthenticatedBookingArtistIdRouteImport.update({
    id: '/booking/$artistId',
    path: '/booking/$artistId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBookingIdConfirmRoute =
  AuthenticatedBookingIdConfirmRouteImport.update({
    id: '/booking/$id/confirm',
    path: '/booking/$id/confirm',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/account': typeof AuthenticatedAccountRoute
  '/favourites': typeof AuthenticatedFavouritesRoute
  '/support': typeof AuthenticatedSupportRoute
  '/artist/$slug': typeof ArtistSlugRoute
  '/booking/$artistId': typeof AuthenticatedBookingArtistIdRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/booking/$id/confirm': typeof AuthenticatedBookingIdConfirmRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/account': typeof AuthenticatedAccountRoute
  '/favourites': typeof AuthenticatedFavouritesRoute
  '/support': typeof AuthenticatedSupportRoute
  '/artist/$slug': typeof ArtistSlugRoute
  '/booking/$artistId': typeof AuthenticatedBookingArtistIdRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/booking/$id/confirm': typeof AuthenticatedBookingIdConfirmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/favourites': typeof AuthenticatedFavouritesRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/artist/$slug': typeof ArtistSlugRoute
  '/_authenticated/booking/$artistId': typeof AuthenticatedBookingArtistIdRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/_authenticated/booking/$id/confirm': typeof AuthenticatedBookingIdConfirmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/search'
    | '/account'
    | '/favourites'
    | '/support'
    | '/artist/$slug'
    | '/booking/$artistId'
    | '/api/auth/me'
    | '/booking/$id/confirm'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/search'
    | '/account'
    | '/favourites'
    | '/support'
    | '/artist/$slug'
    | '/booking/$artistId'
    | '/api/auth/me'
    | '/booking/$id/confirm'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/search'
    | '/_authenticated/account'
    | '/_authenticated/favourites'
    | '/_authenticated/support'
    | '/artist/$slug'
    | '/_authenticated/booking/$artistId'
    | '/api/auth/me'
    | '/_authenticated/booking/$id/confirm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SearchRoute: typeof SearchRoute
  ArtistSlugRoute: typeof ArtistSlugRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/$slug': {
      id: '/artist/$slug'
      path: '/artist/$slug'
      fullPath: '/artist/$slug'
      preLoaderRoute: typeof ArtistSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favourites': {
      id: '/_authenticated/favourites'
      path: '/favourites'
      fullPath: '/favourites'
      preLoaderRoute: typeof AuthenticatedFavouritesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/booking/$artistId': {
      id: '/_authenticated/booking/$artistId'
      path: '/booking/$artistId'
      fullPath: '/booking/$artistId'
      preLoaderRoute: typeof AuthenticatedBookingArtistIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/booking/$id/confirm': {
      id: '/_authenticated/booking/$id/confirm'
      path: '/booking/$id/confirm'
      fullPath: '/booking/$id/confirm'
      preLoaderRoute: typeof AuthenticatedBookingIdConfirmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedFavouritesRoute: typeof AuthenticatedFavouritesRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedBookingArtistIdRoute: typeof AuthenticatedBookingArtistIdRoute
  AuthenticatedBookingIdConfirmRoute: typeof AuthenticatedBookingIdConfirmRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedFavouritesRoute: AuthenticatedFavouritesRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedBookingArtistIdRoute: AuthenticatedBookingArtistIdRoute,
  AuthenticatedBookingIdConfirmRoute: AuthenticatedBookingIdConfirmRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SearchRoute: SearchRoute,
  ArtistSlugRoute: ArtistSlugRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
